services:
  postgres:
    image: postgres:15-alpine
    container_name: coffee-db
    environment:
      POSTGRES_DB: mvst-coffee-challenge-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./frontend/src/lib/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - coffee-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: coffee-app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mvst-coffee-challenge-db
      - DB_USER=postgres
      - DB_PASSWORD=1234
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - coffee-network
    restart: unless-stopped

networks:
  coffee-network:
    driver: bridge